#!/bin/bash

rm sig_vs_cut.out

for cut in 4.0 8.0 10.0 12.0 16.0 20.0
do

sig=`head -1 sig_1.$cut.out | awk '{print $2}'` 
Se=`head -1 Se_1.$cut.out | awk '{print $2}'` 
Df=`head -1 Def_1.$cut.out | awk '{print $2}'` 

echo $cut $sig $Se $Df >> sig_vs_cut.out

done

